<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HA2OUC3" ignored="9" name="Test(failed)" tests="6" failures="6" timestamp="14 Dec 2021 14:42:53 GMT" time="0.432" errors="0">
  <testcase name="tc1" time="0.074" classname="org.rerun.Company">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Company.tc1(Company.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc3" time="0.01" classname="org.rerun.Company">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Company.tc3(Company.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc6" time="0.012" classname="org.rerun.Sample">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Sample.tc6(Sample.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc6 -->
  <testcase name="tc9" time="0.006" classname="org.rerun.Sample">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Sample.tc9(Sample.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc9 -->
  <testcase name="tc13" time="0.008" classname="org.rerun.Employee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Employee.tc13(Employee.java:20)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc13 -->
  <testcase name="tc14" time="0.011" classname="org.rerun.Employee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Employee.tc14(Employee.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc14 -->
  <testcase name="tc11" time="0.0" classname="org.rerun.Employee">
    <ignored/>
  </testcase> <!-- tc11 -->
  <testcase name="tc12" time="0.0" classname="org.rerun.Employee">
    <ignored/>
  </testcase> <!-- tc12 -->
  <testcase name="tc15" time="0.0" classname="org.rerun.Employee">
    <ignored/>
  </testcase> <!-- tc15 -->
  <testcase name="tc10" time="0.0" classname="org.rerun.Sample">
    <ignored/>
  </testcase> <!-- tc10 -->
  <testcase name="tc4" time="0.0" classname="org.rerun.Company">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase name="tc7" time="0.0" classname="org.rerun.Sample">
    <ignored/>
  </testcase> <!-- tc7 -->
  <testcase name="tc8" time="0.0" classname="org.rerun.Sample">
    <ignored/>
  </testcase> <!-- tc8 -->
  <testcase name="tc2" time="0.0" classname="org.rerun.Company">
    <ignored/>
  </testcase> <!-- tc2 -->
  <testcase name="tc5" time="0.0" classname="org.rerun.Company">
    <ignored/>
  </testcase> <!-- tc5 -->
</testsuite> <!-- Test(failed) -->
